update error message

diff --git a/bin/ApplyVariables b/bin/ApplyVariables
--- a/bin/ApplyVariables
+++ b/bin/ApplyVariables
@@ -30,8 +30,11 @@ filename=$(Arg 1)          # source filename
 # find/expand enviornment variables in contents
 # output expanded results to stdout
 ApplyVariablesCore "${open}" "${close}" "${filename}"
-if [[ "$?" != "0" ]]
+
+# if the function returns an error (commonly, if the file doesn't exist)
+# throw an error and abort
+if (( $? != 0 ))
 then
-    Die "'${filename}' failed"
+    Die "${filename}: failed"
 fi
 
