revert core logic to python3, for speed

diff --git a/bin/ApplyVariables b/bin/ApplyVariables
--- a/bin/ApplyVariables
+++ b/bin/ApplyVariables
@@ -24,40 +24,14 @@ if Is_Entry 'identifier'   # variable name prefix (default '')
 then
    open="${open}$(Entry identifier)_"
 fi
+filename=$(Arg 1)          # source filename
 
-# read $(Arg 1)
-# replace variables with env values
-# output result to stdout
-while IFS= read -r line
-do
-   # expand ALL variables in line
-   while true
-   do
-      # remove everything before the first occurance of ${open}
-      # then, remove everything after the first occurance of ${close}
-      # if at either step nothing is removed, goto next line
-      line_post_open="${line#*${open}}"
-      if [[ "${line_post_open}" == "${line}" ]]
-      then
-         break
-      fi
-      line_post_close="${line_post_open%%${close}*}"
-      if [[ "${line_post_close}" == "${line_post_open}" ]]
-      then
-         break
-      fi
-      variable_name="${line_post_close}"
-
-      # lookup the variable in the enviornment hashtable
-      # NOTE: using python3 rather than `eval` for saftey
-      variable_value=$(EvalEnvVar "${variable_name}")
-
-      # substitute all occurances with the variable_value
-      line="${line//${open}${variable_name}${close}/${variable_value}}"
-   done
-   
-   # output substituted line to stdout
-   echo "${line}"
-
-done < "$(Arg 1)"
+# read contents of the ${filename} file
+# find/expand enviornment variables in contents
+# output expanded results to stdout
+ApplyVariablesCore "${open}" "${close}" "${filename}"
+if [[ "$?" != "0" ]]
+then
+    Die "'${filename}' failed"
+fi
 
